input_data_file: 'data/coinbase_hourly.csv'
reward_strategy: 'sortino'
model: 'ppo'
testSubDirs: ['1']
dataset_percentage: 1
n_jobs: 1             # number of parallel jobs
n_trials: 2           # maximum number of trials for finding the best hyperparams
n_test_episodes: 2    # number of test episodes per trial
n_evaluations: 4      # number of evaluations for pruning per trial